// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwlOChGLt1IWyioAmX7heK7-bx_lWsi0Q',
    appId: '1:938448723456:web:74244431bdf6c1b51582e5',
    messagingSenderId: '938448723456',
    projectId: 'startsa-ea49e',
    authDomain: 'startsa-ea49e.firebaseapp.com',
    storageBucket: 'startsa-ea49e.firebasestorage.app',
    measurementId: 'G-Y1XQF1JBQ1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7WlPAmIUI4jk5TzbtMBEtl5F5vXMNQrg',
    appId: '1:938448723456:android:ac296d037d3546c81582e5',
    messagingSenderId: '938448723456',
    projectId: 'startsa-ea49e',
    storageBucket: 'startsa-ea49e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkdAh3eEwY_j9Eml1j1Sy23FVnIaDKFcE',
    appId: '1:938448723456:ios:764819a3ae9012e81582e5',
    messagingSenderId: '938448723456',
    projectId: 'startsa-ea49e',
    storageBucket: 'startsa-ea49e.firebasestorage.app',
    iosBundleId: 'com.example.startsa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBkdAh3eEwY_j9Eml1j1Sy23FVnIaDKFcE',
    appId: '1:938448723456:ios:764819a3ae9012e81582e5',
    messagingSenderId: '938448723456',
    projectId: 'startsa-ea49e',
    storageBucket: 'startsa-ea49e.firebasestorage.app',
    iosBundleId: 'com.example.startsa',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBwlOChGLt1IWyioAmX7heK7-bx_lWsi0Q',
    appId: '1:938448723456:web:6c2114d2b510d3b51582e5',
    messagingSenderId: '938448723456',
    projectId: 'startsa-ea49e',
    authDomain: 'startsa-ea49e.firebaseapp.com',
    storageBucket: 'startsa-ea49e.firebasestorage.app',
    measurementId: 'G-ZELVM2Z9VQ',
  );
}
